---
- name: Install required packages
  apt:
    name: "{{ item }}"
    state: present
    allow_unauthenticated: yes
    update_cache: yes
  with_items:
    - nodejs
    - build-essential
    - npm
    - python-pip
    - redis-server

- name: Create symbolic link node for nodejs
  file:
    src: /usr/bin/nodejs
    path: /usr/bin/node
    state: link

- name: Create folder to place load balancer files
  file:
    path: /etc/git/load_balancer
    state: directory

- name: copy load_balancer files
  copy:
    src: files/{{item}}
    dest: /etc/git/load_balancer/
  with_items:
    - load_balancer.js
    - package.json

- name: create checkbox servers file
  template:
    src: checkbox_servers.j2
    dest: /etc/git/load_balancer/checkbox_servers

- name: Create folder to place redis-client files
  file:
    path: /etc/git/redis-client
    state: directory

- name: copy redis-client files
  copy:
    src: files/redis-client.js
    dest: /etc/git/redis-client/

- name: copy redis-client files
  copy:
    src: files/package_redis-cli.json
    dest: /etc/git/redis-client/package.json

- name: run npm install for load_balancer
  shell: npm install
  args:
    chdir: /etc/git/load_balancer/

- name: run npm install for redis-client
  shell: npm install
  args:
    chdir: /etc/git/redis-client/

- name: "Install forever to run load_balancer proxy server"
  shell: npm install -g forever

- name: stop previous verison of forever runs
  shell: forever stopall
  become: no

- name: start load balancer
  shell: forever start --watch --watchDirectory ./ load_balancer.js
  become: no
  args:
    chdir: /etc/git/load_balancer/

- name: start redis-client
  shell: forever start --watch --watchDirectory ./ redis-client.js
  become: no
  args:
    chdir: /etc/git/redis-client/
