---
- hosts: localhost
  gather_facts: False
  become: False
  pre_tasks:
    - name: install python 2
      raw: test -e /usr/bin/python || (sudo apt -y update && sudo apt install -y python-minimal)
      changed_when: False
    - setup:
  vars:
    iTrust_inventory_path: "{{ playbook_dir }}"
    checkbox_inventory_path: "{{ playbook_dir }}"
    host1_key: deployment_env.pem
    host2_key: deployment_env.pem
    host3_key: deployment_env.pem
    host4_key: deployment_env.pem
    host5_key: deployment_env.pem
    host6_key: deployment_env.pem
  vars_prompt:
    - name: AWS_ACCESS_KEY_ID
      prompt: "Enter AWS access key id"
      private: yes
    - name: AWS_SECRET_ACCESS_KEY
      prompt: "Enter AWS secret access key"
      private: yes
  roles:
    - role: provision_ec2

- hosts: jenkins
  gather_facts: False
  become: True
  pre_tasks:
    - name: install python 2
      raw: test -e /usr/bin/python || (sudo apt -y update && sudo apt install -y python-minimal)
      changed_when: False
    - setup:
  vars_prompt:
    - name: username
      prompt: "Enter remote username for Jenkins"
      private: no
    - name: jenkinspassword
      prompt: "Enter remote password for Jenkins"
      private: yes
    - name: gitent_username
      prompt: "Enter ncsu github username for iTrust"
      private: no
    - name: gitent_password
      prompt: "Enter ncsu github Password"
      private: yes
    - name: github_username
      prompt: "Enter github username for checkbox.io"
      private: no
    - name: github_password
      prompt: "Enter github Password"
      private: yes

  roles:
    - role: jenkins_setup
    - role: itrust_jenkins_job_setup
    - role: checkboxio_jenkins_job_setup

...
