---
all:
  hosts:
    localhost:
      ansible_connection: local
      ec2_ip_file_address: /etc/ec2info

    jenkins:
      ansible_ssh_host: 192.168.33.10
      ansible_ssh_user: ubuntu
      ansible_ssh_private_key_file : jenkins_host.pem
      post_build_playbook_path: /etc/playbooksRepo/devops-milestone3
...
