Vagrant.configure('2') do |config|

  config.vm.box = 'ubuntu/xenial64'

  config.vm.provider :virtualbox do |vb|
    vb.customize [ 'modifyvm', :id, '--natdnshostresolver1', 'on' ]
  end

  config.vm.define :nomad_server do |machine|

    machine.vm.network 'private_network', ip: '192.168.33.11'
    machine.vm.synced_folder '.vagrant/machines/', '/ssh'

  end

  config.vm.define :nomad1 do |machine|

    machine.vm.network 'private_network', ip: '192.168.33.12'

  end

  config.vm.define :nomad2 do |machine|

    machine.vm.network 'private_network', ip: '192.168.33.13'

  end

  config.vm.define :nomad3 do |machine|

    machine.vm.network 'private_network', ip: '192.168.33.14'

  end

end