- name: Import public key for mongodb
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: EA312927
    state: present
    validate_certs: no

- name: Add mongodb source
  apt_repository:
    repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 multiverse
    state: present
    update_cache: yes

- name: Install required packages
  apt:
    name: "{{ item }}"
    state: present
    allow_unauthenticated: yes
    update_cache: yes
  with_items:
    - mongodb
    - build-essential

- name: Create a mongodb service
  copy:
    src: mongodb.service
    dest: /etc/systemd/system

- name: Start mongodb service and make it available after bootup
  service:
    name: mongodb
    state: started
    enabled: yes

- name: Add admin user to mongodb
  mongodb_user:
    database: admin
    name: admin
    password: "{{ mongodb_password }}"
    state: present
    roles: userAdminAnyDatabase

- name: Restart mongodb service
  service:
    name: mongodb
    state: restarted