---
- name: Install Redis
  hosts: localhost
  become: true
  become_method: sudo
  vars:
    redis_port: 6379
    redis_databases: 1
  tasks:
   - name: Install dependencies of Redis
     apt:
       pkg: "{{ item }}"
       state: present
       update_cache: yes
     with_items:
      - gcc
      - make
      - libc6-dev

   - name: Download Redis
     apt_repository:
        repo: 'ppa:chris-lea/redis-server'
        state: present

   - name: apt-get update_cache
     apt:
      update_cache: yes

   - name: Ensure Redis is present
     apt: pkg=redis-server state=latest

   - name: Start Redis
     service: name=redis state=started

   - name: add ip address in conf file
     replace:
       dest: /etc/redis/redis.conf
       regexp: 'bind 127.0.0.1'
       replace: 'bind 127.0.0.1 192.168.33.30'

   - name: Restart redis service
     shell: systemctl restart redis-server.service

   - name: Allow 6379 through firewall
     shell: ufw allow 6379
   
   - name: master task - changing tcp keepalive to 60
     replace:
       dest: /etc/redis/redis.conf
       regexp: 'tcp-keepalive 300'
       replace: 'tcp-keepalive 60'

   - name: master task - creating redis master password
     replace:
       dest: /etc/redis/redis.conf
       regexp: '# requirepass foobared'
       replace: 'requirepass abcde'

   - name: master task - updating maxmemory-policy
     replace:
       dest: /etc/redis/redis.conf
       regexp: '# maxmemory-policy noeviction'
       replace: 'maxmemory-policy noeviction'

   - name: master task - updating appendonly mode
     replace:
       dest: /etc/redis/redis.conf
       regexp: 'appendonly no'
       replace: 'appendonly yes'

   - name: master task - updating appendonly file
     replace:
       dest: /etc/redis/redis.conf
       regexp: 'appendfilename "appendonly.aof"'
       replace: 'appendfilename "redis-staging-ao.aof"'

   - name: Restart redis service
     shell: systemctl restart redis-server.service