---
- name: Install Redis
  hosts: localhost
  become: true
  become_method: sudo
  vars:
    redis_port: 6379
    redis_databases: 1
  tasks:
   - name: Install dependencies of Redis
     apt:
       pkg: "{{ item }}"
       state: present
       update_cache: yes
     with_items:
      - gcc
      - make
      - libc6-dev

   - name: Download Redis
     apt_repository:
        repo: 'ppa:chris-lea/redis-server'
        state: present

   - name: apt-get update_cache
     apt:
      update_cache: yes

   - name: Ensure Redis is present
     apt: pkg=redis-server state=latest

   - name: Start Redis
     service: name=redis state=started

   - name: add ip address in conf file
     replace:
       dest: /etc/redis/redis.conf
       regexp: 'bind 127.0.0.1'
       replace: 'bind 127.0.0.1 192.168.33.50'

   - name: Restart redis service
     shell: systemctl restart redis-server.service

   - name: Allow 6379 through firewall
     shell: ufw allow 6379
   
   - name: slave task - update slave of ip and port
     replace:
       dest: /etc/redis/redis.conf
       regexp: '# slaveof <masterip> <masterport>'
       replace: 'slaveof 192.168.33.30 6379'

   - name: slave task - updating redis master password
     replace:
       dest: /etc/redis/redis.conf
       regexp: '# masterauth <master-password>'
       replace: 'masterauth abcde'

   - name: Restart redis service
     shell: systemctl restart redis-server.service