---

- name: Install java 8
  include_role:
    name: java8_setup
    private: yes

- name: Install mysql-server
  include_role:
    name: mysql_setup
    private: yes

- name: Add ansible repository
  apt_repository:
    repo: 'ppa:ansible/ansible'
    state: present
    update_cache: yes

- name: Installing other required packages
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - maven
    - git
    - git-core
    - python-software-properties
    - ansible
    - python-pip

- name: Install pip packages
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - python-jenkins
    - lxml

- name: Create itrust job
  jenkins_job:
    name: itrust-packaging-job
    config: "{{ lookup('template','itrust.xml.j2') }}"
    url: http://localhost:8080
    user: "{{ username }}"
    password: "{{ jenkinspassword }}"
    state: present

- name: Get playbook for post build ansible scripts
  include_role:
    name: clone_playbook

- name: stat /etc/iTrust_mysql_config
  stat:
    path: /etc/iTrust_mysql_config
  register: iTrust_mysql_config_stat

- name: Ensure that directory exists for copying context.xml
  file:
    path: /etc/iTrust_mysql_config
    state: directory
  when: iTrust_mysql_config_stat.stat.exists == False

- name: Copy iTrust context.xml for mysql
  template:
    src: context.xml.j2
    dest: /etc/iTrust_mysql_config/context.xml
    mode: 0666
...
