---
- name: Checking if the path to iTrust war exists
  local_action:
    module: stat
    path: "{{ iTrust_war_path }}"
  register: check_iTrust_Path

- fail:
    msg: "The war file is not found at {{ iTrust_war_path }} and {{ check_iTrust_Path.stat.exists }}"
  when: check_iTrust_Path.stat.exists == False

- name: Install tomcat
  include_role:
    name: tomcat_setup
    private: yes

- name: Copy the iTrust war file to Tomcat's deployment folder
  copy:
    src: "{{ iTrust_war_path }}"
    dest: "/opt/tomcat9/webapps/iTrust.war"

- name: Shutdown Tomcat
  shell: nohup sh /opt/tomcat9/bin/shutdown.sh

- pause:
    minutes: 1

- name: Start Tomcat
  shell: nohup sh /opt/tomcat9/bin/startup.sh
...
