---
- name: stat /etc/playbooksRepo
  stat:
    path: /etc/playbooksRepo
  register: playbooksRepoStat

- name: Ensure that directory exists for cloning
  file:
    path: /etc/playbooksRepo
    state: directory
  when: playbooksRepoStat.stat.exists == False

- name: stat "{{ post_build_playbook_path }}"
  stat:
    path: "{{ post_build_playbook_path }}"
  register: postBuildDirStat

- name: Clone playbook to run jenkins post build scripts
  command: git clone https://{{gitent_username}}:{{gitent_password}}@github.ncsu.edu/akshetty/devops-milestone3.git
  args:
    chdir: /etc/playbooksRepo
  when: postBuildDirStat.stat.exists == False

- name: Pull latest playbooksRepo
  command: git pull
  args:
    chdir: "{{ post_build_playbook_path }}"
  when: postBuildDirStat.stat.exists == True

- name: Transfer remote server certificates
  copy:
    src: "{{ item }}"
    dest: "{{ post_build_playbook_path }}"
    mode: 0600
    owner: jenkins
    group: jenkins
  with_items:
    - deployment_env.pem
    - iTrust_inventory
    - checkbox_inventory
...
